### ISSUE TITLE
Not work long break

### ISSUE THREAD

**Issue by BlackGrizzly** [slgobinath/SafeEyes#239] opened 2018-02-05 08:27 UTC
Not work long break. Long break interval 60min. Long Break duration 600sec

Version 2.0.2
Ubuntu 16.04LTS

**Comment by slgobinath** [comment] 2018-02-09 11:59
Hi,
Could you please share your system locale (Output of `locale` command in terminal)?

**Comment by BlackGrizzly** [comment] 2018-02-09 12:15
LANG=ru_RU.UTF-8
LANGUAGE=ru:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=

**Comment by slgobinath** [comment] 2018-02-09 12:25
A similar issue was reported here: https://github.com/slgobinath/SafeEyes/issues/229. but still, I am unable to find the root cause.
There is a high chance of its being fixed by https://github.com/slgobinath/SafeEyes/commit/992b091cf768afaa8718056adccc47893ae11962. Could you please test the master branch and let me know whether it has been fixed?

To run Safe Eyes from master branch, please follow these steps:
1. Clone the GitHub repository:
```
git clone https://github.com/slgobinath/SafeEyes.git
```
2. Chnage the directry to SafeEyes
```
cd SafeEyes
```
3. Run Safe Eyes
```
python3 -m safeeyes
```

**Comment by BlackGrizzly** [comment] 2018-02-09 14:07
It is work!

**Comment by slgobinath** [comment] 2018-02-09 14:27
Thanks for confirming. I am releasing a new version :-)

**Comment by slgobinath** [comment] 2018-02-09 14:49
The new version is released and available for Ubuntu 16.04.

**Closed by slgobinath** 2018-02-09 14:49 UTC

**Comment by BlackGrizzly** [comment] 2018-02-15 08:52
2.0.4 not work

**Comment by icedd** [comment] 2018-03-06 15:20
2.0.4 Long breaks are not working for me.

**Comment by Niakr1s** [comment] 2018-03-19 11:13
2.0.4 doesn't work, here is my locale

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=

**Comment by slgobinath** [comment] 2018-03-19 11:28
Hi,
This issue has been fixed in https://github.com/slgobinath/SafeEyes/commit/32cc7aaf35d4a5e0cafc2fa85601264db98bc7be but I was waiting to include to some more features which I couldn't due to my busy schedule. I will release the new version containing the fix today.

**Comment by Niakr1s** [comment] 2018-03-19 11:29
Okay, thank you. Waiting for release!

**Comment by slgobinath** [comment] 2018-03-19 22:18
New version 2.0.5 is released with the fix

**Comment by icedd** [comment] 2018-03-20 14:53
Thank you for pushing 2.0.5. I am just starting my work day and will test that it works for me and let you know. 

Great program by the way.

**Comment by borisPristupa** [comment] 2018-10-28 20:50
Hi,
Same issue with just installed 2.0.6.

Lubuntu 18.04,
locale command's output:

> LANG=en_US.UTF-8
> LANGUAGE=en
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=ru_RU.UTF-8
> LC_TIME=ru_RU.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY=ru_RU.UTF-8
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER=ru_RU.UTF-8
> LC_NAME=ru_RU.UTF-8
> LC_ADDRESS=ru_RU.UTF-8
> LC_TELEPHONE=ru_RU.UTF-8
> LC_MEASUREMENT=ru_RU.UTF-8
> LC_IDENTIFICATION=ru_RU.UTF-8
> LC_ALL=

**Comment by slgobinath** [comment] 2018-10-29 01:35
Hi @borisPristupa,

Could you try this fix and let me know the results?

1. Quit currently running Safe Eyes
2. Remove the directory `~/.config/safeeyes`
    ```
    rm -rf ~/.config/safeeyes
    ````
3. Start Safe Eyes again and see whether you get long breaks.

**Comment by borisPristupa** [comment] 2018-10-29 19:41
Well, it worked just until I changed the settings. 
I changed long break duration to 75, turned off "Do not disturb" and increased "Smart Pause" idle time to 60.

**Comment by borisPristupa** [comment] 2018-10-30 04:40
```
{
    "allow_postpone": false,
    "break_interval": 15,
    "long_break_duration": 75,
    "long_breaks": [
        {
            "name": "Walk for a while"
        },
        {
            "name": "Lean back at your seat and relax"
        }
    ],
    "meta": {
        "config_version": "6.0.0"
    },
    "no_of_short_breaks_per_long_break": 5,
    "persist_state": false,
    "plugins": [
        {
            "enabled": false,
            "id": "donotdisturb",
            "settings": {
                "skip_break_windows": "",
                "take_break_windows": "",
                "unfullscreen": true,
                "while_on_battery": false
            },
            "version": "0.0.2"
        },
        {
            "enabled": true,
            "id": "notification",
            "version": "0.0.1"
        },
        {
            "enabled": true,
            "id": "audiblealert",
            "settings": {
                "pre_break_alert": true
            },
            "version": "0.0.2"
        },
        {
            "enabled": true,
            "id": "trayicon",
            "settings": {
                "disable_options": [
                    {
                        "time": 30,
                        "unit": "minute"
                    },
                    {
                        "time": 1,
                        "unit": "hour"
                    },
                    {
                        "time": 2,
                        "unit": "hour"
                    },
                    {
                        "time": 3,
                        "unit": "hour"
                    }
                ],
                "show_time_in_tray": false
            },
            "version": "0.0.1"
        },
        {
            "enabled": true,
            "id": "smartpause",
            "settings": {
                "idle_time": 60.0,
                "interpret_idle_as_break": false
            },
            "version": "0.0.2"
        },
        {
            "enabled": true,
            "id": "screensaver",
            "settings": {
                "command": "",
                "min_seconds": 3
            },
            "version": "0.0.1"
        },
        {
            "enabled": false,
            "id": "healthstats",
            "version": "0.0.1"
        }
    ],
    "postpone_duration": 5,
    "pre_break_warning_time": 10,
    "rpc_port": 7200,
    "short_break_duration": 15,
    "short_breaks": [
        {
            "name": "Tightly close your eyes"
        },
        {
            "name": "Roll your eyes a few times to each side"
        },
        {
            "name": "Rotate your eyes in clockwise direction"
        },
        {
            "name": "Rotate your eyes in counterclockwise direction"
        },
        {
            "name": "Blink your eyes"
        },
        {
            "name": "Focus on a point in the far distance"
        },
        {
            "name": "Have some water"
        }
    ],
    "shortcut_disable_time": 2,
    "shortcut_postpone": 65,
    "shortcut_skip": 9,
    "strict_break": false
}
```
