### ISSUE TITLE
Safe Eyes breaks cause Tor browser to quit in Ubuntu 20.10

### ISSUE THREAD

**Issue by Aanai** [slgobinath/SafeEyes#395] opened 2020-11-18 20:41 UTC
Ever since I upgraded to Ubuntu 20.10 from Ubuntu 20.04 SafeEyes breaks have been causing glitches. When the breaks start, the other open windows take 5 seconds or so to completely disappear and the screen to turn black (break screen), sometimes even longer--almost the duration of the break itself! My graphics divers are up to date. I have an Intel graphics card. But the biggest problem is that every time there is a SafeEyes break, my Tor browser closes automatically (if I am using it when the break starts). How do I fix this?

**Comment by slgobinath** [comment] 2020-12-25 18:00
I think this is same as the https://github.com/slgobinath/SafeEyes/issues/392
Above bug is fixed and a new version is released with the fix. Please let me know if the problem is still there with Safe Eyes 2.1.0

**Closed by slgobinath** 2020-12-25 18:00 UTC
