### ISSUE TITLE
Displays black screen in new workspace in elementary OS Loki

### ISSUE THREAD

**Issue by Gabriel-p** [slgobinath/SafeEyes#17] opened 2016-11-02 13:30 UTC
I'm using [elementary OS](https://elementary.io) Freya 64-bit. It is based on Ubuntu 16.04.

I see no messages with exercises on long breaks, just the black screen.

**Comment by slgobinath** [comment] 2016-11-03 04:00
Could you please provide some more details.
 * Are you using multiple monitors?
 * Do short breaks show the exercises?
 * Is it reproducible? (Happens for all long breaks or randomly occurs)

**Comment by Gabriel-p** [comment] 2016-11-03 12:00
Not using multiple monitors.
No breaks shows any exercise.
Happens every time.

Perhaps this is related to workspaces? I noticed that the app launches the break on a new workspace, instead of the current one. This is also reproducible always.

**Comment by Gabriel-p** [comment] 2016-11-03 14:23
I figured out the issue, and it is indeed related to the workspaces in elementary OS.

When the app starts a break, it switches to a new workspace where a simple black screen is shown. But the original workspace is indeed showing the exercises and the time counter.

Not sure why the app creates a second instance in a new workspace, showing just a black screen. This is the issue that needs to be fixed.

Let me know if I can help you debug this.

**Comment by slgobinath** [comment] 2016-11-04 01:38
This is the behavior in multi-monitor system. Showing an empty screen in non-active monitor and the count down in the active monitor. I will test it in elementary and release the fix soon. Thanks a lot for your effort and reporting the issue.

**Comment by slgobinath** [comment] 2016-11-05 00:59
I have tested in Loki but couldn't reproduce. I'll test it in Freya and let you know.

**Comment by Gabriel-p** [comment] 2016-11-05 01:55
Sorry @slgobinath, I'm using Loki (64 bit) not Freya.

I have an Nvidia card and am using the 340.98 binary.

**Comment by slgobinath** [comment] 2016-11-05 02:31
Could you please check the number of displays shown in `Displays` app. I remember one of my friend's laptop had such a problem which showed two displays even without connecting external monitor/projector.

**Comment by Gabriel-p** [comment] 2016-11-05 03:06
Sorry again @slgobinath, but I actually *do* have a second monitor. It is really a TV connected through HDMI, so I didn't think of it as a "second monitor" at first.

I just tried unplugging the HDMI cable and the screen now *does* show properly, i.e.: in the (single) monitor I'm using, and in the proper workspace.

So the issue is that when a second monitor is plugged in, the app mistakenly shows a black screen in the monitor I'm using, and the break screen in the other monitor (a TV in my case), when it should be the other way around.

**Comment by slgobinath** [comment] 2016-11-05 03:44
No worries :-)
The expected behavior is showing the countdown in the active monitor (The one you are working on, when the break is about to start. It is determined by the active window's location). May I know whether you were working on TV or Computer screen when the break screen appears?

**Comment by Gabriel-p** [comment] 2016-11-05 13:57
The countdown does show in the active monitor properly, the issue is with the break screen. They show "switched", the full black screen shows in the active monitor en the break screen shows somewhere else.

I'm always working on my computer when this happens, the TV is connected but not even on (I can reproduce this always).

**Comment by slgobinath** [comment] 2016-11-06 07:25
I will check this and release the fix in next version. (It may take some time as I do not use elementary as my major OS and I do not have an external monitor/projector for testing purposes)

**Comment by slgobinath** [comment] 2016-11-08 13:51
@Gabriel-p Could you please help me on testing the fix I have implemented. If possible, please try this and let me know the result:
1. Remove the safeeys configf directory:  `rm -r ~/.config/safeeyes` (No need to remove the current Safe Eyes installation)
2. Download the [ fix-bug-due-to-multiple-displays](https://github.com/slgobinath/SafeEyes/tree/fix-bug-due-to-multiple-displays) branch and move to [safeeyes/safeeyes](https://github.com/slgobinath/SafeEyes/tree/fix-bug-due-to-multiple-displays/safeeyes/safeeyes) directory
3. Open terminal and execute `./safeeyes`

I have added the Skip button, message and count down to all the break screens. Please let me know the output.

Thanks in advance

**Comment by Gabriel-p** [comment] 2016-11-08 14:55
Ok, here are some comments:

1. The new notice at the top of the pop up does not update itself if the `Interval between two breaks` is modified in the settings.
1. The break screen is now correctly focused when triggered, but it still spawns in a new workspace rather than the one being used. This is a minor issue since once the break screen is gone, one can easily go back to the original workspace.
1. The second break screen that appeared ("*Roll your eyes*") got down to 00:01 and it just stopped there. I could not skip it either since the `Skip` button did nothing when pressed. I had to manually shut it down.
1. The third break screen ("*Rotate your eyes in clockwise direction*") showed with a broken timer (it only displayed `00`), and again the `Skip` button did not work.

I terminated the application after this.

**Comment by slgobinath** [comment] 2016-11-08 23:43
Thanks @Gabriel-p. Thanks a lot your support. I will test it further and release the product later. Until I release a new version, you can use [v1.0.7](https://github.com/slgobinath/SafeEyes/releases/tag/v1.0.7) because it does not have multi-monitor support. (Please remove the `.config/safeeyes` directory before starting v1.0.7)

**Comment by Gabriel-p** [comment] 2016-11-08 23:45
Of course @slgobinath, let me know if there's anything else I can help you with.

**Comment by slgobinath** [comment] 2016-11-14 01:43
Hi @Gabriel-p I need your help again. I have modified the fix in  fix-bug-due-to-multiple-displays branch. Could you please test this branch as you did earlier and let me know the behavior.

(I have purposely disabled the keyboard lock and above other screens feature to make testing less painful. In case you have any issues you can quit the app either from tray menu or from terminal)

**Comment by Gabriel-p** [comment] 2016-11-14 20:41
Hi @slgobinath. I've been trying the new branch throughout the day and it seems to work fine.
The only (minor) glitches that remain are the two first ones I mentioned:

1. The `Next break` notice at the top of the pop up does not update itself if the `Interval between two breaks` is modified in the settings.
1. The break screen is correctly focused when triggered, but it still spawns in a new workspace rather than the one being used.

**Comment by slgobinath** [comment] 2016-11-14 22:54
Thanks a lot @Gabriel-p. The next break issue is already fixed in the main branch and I hope the new workspace problem is something related to Elementary OS. I wonder whether it automatically moves the fullscreen windows to new workspace. However, I can focus on that issue in later versions. I'll release the new version with the patch.
Once again, thank you for your support to make Safe Eyes a better application :-)

**Comment by slgobinath** [comment] 2016-11-15 13:59
Fixed with https://github.com/slgobinath/SafeEyes/commit/98344aaa93c9c1452e456b462bc43c09cc028756 and included in release [v1.1.0](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.0)

**Closed by slgobinath** 2016-11-15 13:59 UTC
Labels: bug
