### ISSUE TITLE
New release with Python 3.12 support?

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#552] opened 2023-12-03 14:55 UTC
Hi!

@slgobinath pull request #544 fixed support for Python 3.12 but there is no new release so that Linux distros will need to cherry-pick commits and add them as patches downstream if there is no new release. That's a bit unfortunate. Is there a chance you could cut a new release from `master`?

Best, Sebastian

**Comment by AdamPS** [comment] 2023-12-20 20:02
Yes I am aware of the benefits of creating a release😃. slgobinath is mostly away, he made me a co-maintainer, but I only have a little time. We are aiming to keep this project alive however please be patient.

**Comment by AdamPS** [comment] 2023-12-20 20:03
(Closing as it's not a bug😃)

**Comment by hartwork** [comment] 2023-12-20 20:33
@AdamPS I don't see how it's helping to close this without a release, but I accept your decision.

**Comment by AdamPS** [comment] 2023-12-21 10:43
OK how about like this?

**Comment by AdamPS** [comment] 2024-01-12 12:27
Proposed steps:

1. Check for any other issues that are a priority and easy to fix. I've just spotted there are 15 open pull requests, mostly fairly recent. Anyone can get involved by reviewing and testing these. Once they are confirmed as ready by a second person then please post a comment here linking the issue, and we can merge.
2. Update any translations?
3. Follow the [how to release](https://github.com/slgobinath/SafeEyes#how-to-release) process.

**Comment by archisman-panigrahi** [comment] 2024-03-05 23:33
Safeeyes is broken on Ubuntu 24.04 due to this issue. Can you please make a release?

**Comment by archisman-panigrahi** [comment] 2024-03-05 23:37
@AdamPS  I can send a pull request with steps 1-5 as described here https://github.com/slgobinath/SafeEyes?tab=readme-ov-file#how-to-release
Please let me know if that would make the job easy for you, since you are busy.

**Comment by vijay-prema** [comment] 2024-04-21 08:51
I noted the flatpak version is still the old 2.1.6 release but works fine on Ubuntu 2404, because I guess it is a standalone container.

You can get it from Flathub, and use it until a new release is made in the ppa that supports Python 3.12.

**Comment by archisman-panigrahi** [comment] 2024-04-25 21:51
Can we just have a new release with whatever commit there is in the master branch?

**Comment by archisman-panigrahi** [comment] 2024-04-29 06:21
I created a pull request (with current master branch + updated version number) to speed up the release process https://github.com/slgobinath/SafeEyes/pull/572

Please note that we need safeeyes to function out of the box in Ubuntu and Fedora. Translations can wait.

**Comment by Nefcanto** [comment] 2024-05-18 05:40
It's unfortunate that even with the help of the community the release is not provided.

**Comment by archisman-panigrahi** [comment] 2024-05-18 18:40
I will be happy to be a co-maintainer on GitHub for managing releases (and only that part, because I am not a proficient python programmer), and I can also maintain the PPA.
(for credibility: Here is the list of PPAs I maintain https://launchpad.net/~apandada1)

**Comment by slgobinath** [comment] 2024-06-08 20:02
Thanks @archisman-panigrahi for stepping in.
I'm no longer able to maintain the Ubuntu PPA. Appreciate it if you could maintain it. Is there a way to give access to you for the existing launchpad? If not feel free to create your own repo and abandon the old one.

**Comment by slgobinath** [comment] 2024-06-08 20:11
2.1.7 is released

**Comment by hartwork** [comment] 2024-06-08 20:49
@slgobinath thanks!

One of the two tags für 2.1.7 seems mistaken — could you delete `vv2.1.7` with double `v`?

![tags_Screenshot_20240608_224751](https://github.com/slgobinath/SafeEyes/assets/1577132/0773f01a-446a-43c1-a8bb-d5b1c9d825ee)

**Comment by slgobinath** [comment] 2024-06-08 20:53
Done

**Comment by hartwork** [comment] 2024-06-08 20:55
@slgobinath thanks!

It turns out that the double `vv` tag has the right content and the single `v` does not. My vote for re-releasing as 2.1.8 also, since packaging tag 2.1.7 would package something incomplete. What do you think?

**Comment by slgobinath** [comment] 2024-06-08 21:18
Sure I'm stepping out. I'll do another release later today.

**Comment by hartwork** [comment] 2024-06-08 21:24
> Sure I'm stepping out.

@slgobinath I'm not 100% what you refer to here. Could you elaborate?

> I'll do another release later today.

Thank you! Please see #578 in case you want to release via a push to branch `release`.

**Comment by slgobinath** [comment] 2024-06-08 22:49
@hartwork thanks for your PR.
Released 2.1.8

**Comment by hartwork** [comment] 2024-06-08 23:22
@slgobinath thank you!

I have [bumped to 2.1.8 in Gentoo just now](https://github.com/gentoo/gentoo/commit/a11e422906cbb521697888a0629676addf9f1d61).

Unfortunately, there is a regression in 2.1.7/2.1.8: #580.

**Comment by archisman-panigrahi** [comment] 2024-06-09 01:37
> Thanks @archisman-panigrahi for stepping in.
> I'm no longer able to maintain the Ubuntu PPA. Appreciate it if you could maintain it. Is there a way to give access to you for the existing launchpad? If not feel free to create your own repo and abandon the old one.

There is no way I can access the existing Launchpad PPA.

Here is the new PPA https://launchpad.net/~safeeyes-team/+archive/ubuntu/safeeyes

I designed it in a way that it is owned by "Safe Eyes" team rather than me, so that in case I have to step down at some point (I promise that it is not happening anytime soon), someone can easily pick it up without needing to create a new PPA. And it is very easy to add/remove members to the team in Launchpad.

I will send a PR with the new PPA link in the README and the website.

For now I only added support for Ubuntu 24.04 and later versions in the PPA (this may change later), because these versions of Ubuntu did not have a working safe eyes version, and older versions of Ubuntu had a working version of safe eyes, and I don't want to introduce regression.

**Comment by archisman-panigrahi** [comment] 2024-06-09 01:48
I guess we can close this issue.

**Comment by archisman-panigrahi** [comment] 2024-06-09 02:07
@slgobinath Can you please edit the description of the old PPA, and add the link to the new PPA, and rename the old PPA to "Safe Eyes (discontinued)"?

**Comment by Nefcanto** [comment] 2024-06-09 04:50
@archisman-panigrahi, thank you so much. I worked.

**Comment by slgobinath** [comment] 2024-06-09 05:24
Updated the old PPA https://launchpad.net/~slgobinath/+archive/ubuntu/safeeyes

**Comment by archisman-panigrahi** [comment] 2024-06-19 03:07
Please close this issue. Most of the major distros (Ubuntu,Fedora,Arch) already have the updated version with python3.12 support.

**Comment by Nefcanto** [comment] 2024-06-19 05:46
@archisman-panigrahi, does this mean that we don't need this code anymore?

```
    sudo add-apt-repository ppa:safeeyes-team/safeeyes -y
    sudo apt-get update
    sudo apt-get install safeeyes -y
```

And we can simply run `sudo apt install safeeyes -y` to install it?

**Comment by archisman-panigrahi** [comment] 2024-06-19 12:21
@Nefcanto No, the PPA is required in Ubuntu 24.04, as Ubuntu (usually) does not update its software during the lifetime of a release. But it should not be required in later versions of Ubuntu, because eventually the Debian developers will package the new version and it will flow down to Ubuntu.

**Closed** 2024-06-19 12:26 UTC
Labels: in progress
