### ISSUE TITLE
MAJOR BUG: Platform files missing

### ISSUE THREAD

**Issue by AdamPS** [slgobinath/SafeEyes#406] opened 2020-12-26 08:52 UTC
I just upgraded to 2.1.1 and now all the platform files are missing.  The problem is this commit https://github.com/slgobinath/SafeEyes/commit/12b2b0b2a4bd4bdda20d55fea4a45096651460be.  Although initialize_platform() would be run for a new install, it isn't run on upgrade from an older version when config files are already present.

**Comment by AdamPS** [comment] 2020-12-26 08:59
Also I think the new approach means that platform files will never be updated on upgrade.  The old way seemed the standard way and very clear.  I thought that .local/share is normally for locally installed programs rather than packages.  So I agree the new code is helpful for people running from source or other non-package ways.  However the old way is maybe good otherwise??

**Comment by AdamPS** [comment] 2020-12-26 09:10
Ah I see it creates links so it's not as bad as I thought.  However I think it would fail to create a new link if an icon was added.

**Comment by AdamPS** [comment] 2020-12-26 09:12
Another thing: it seems that Gnome it doesn't pick up the new icons added to .local/share/icons until a restart.

**Comment by slgobinath** [comment] 2020-12-26 14:54
The problem is Python behaves differently in my system and hopefully in Ubuntu based distributions at least. When I test Safe Eyes 2.1.0, the desktop entry and icons are added to the folder: `/usr/local/lib/python3.8/dist-packages/root/.local/share/applications/safeeyes.desktop` and `/usr/local/lib/python3.8/dist-packages/root/.local/share/icons/hicolor`

I didn't change anything in setup.py and I guess its depending on how Python handles it. In Manjaro I think it works as expected. Some other Python apps also noticed this behavior and switched to similar approach. Could you please help me test this behavior if you are using a non-Arch distribution by installing Safe Eyes 2.1.0 using the following command:

```
sudo pip3 install safeeyes==2.1.0
```

Safe Eyes 2.1.1 creates links for desktop entry and icons whenever you run it. TBH I don't like this option as it leaves broken links if Safe Eyes is uninstalled but I do not have a reliable alternative at the moment.

**Comment by AdamPS** [comment] 2020-12-26 18:08
Thanks for a quick response and a clear explanation - I understand a bit better now.  I am using Ubuntu taking packages from your PPA.

> by installing Safe Eyes 2.1.0 using the following command:
That works

> Safe Eyes 2.1.1 creates links for desktop entry and icons whenever you run it.
Interesting that works for me too.  So I am unsure how I ever saw the bug in the first place.  I will experiment a bit more and report back.

**Comment by AdamPS** [comment] 2020-12-26 18:14
Ah OK I see what the problem was now.

1. When I update to 2.1.1 using apt then the file /usr/share/applications/safeeyes.desktop is removed.
1. As soon as I manage run 2.1.1 for the first time then the file ~/.local/share/applications/safeeyes.desktop is created
2. However I can't use all the normal GUI ways to run because the desktop file is missing.  So it requires a one-off step to run from the command line.

**Comment by slgobinath** [comment] 2020-12-26 20:32
You mean desktop entry is created when you install 2.1.0? In my case it wasn't!!!
I will test it further to see how I can solve the issue. Another option is providing both options.

btw Thank you very much for your donation :-)

**Comment by AdamPS** [comment] 2020-12-27 10:58
> You mean desktop entry is created when you install 2.1.0?
Ah sorry no I don't.  I have /usr/local/lib/python3.8/dist-packages/root/.local/share/applications/safeeyes.desktop but that is not in a location recognised by Gnome.

> providing both options.
Yes that sounds very good to me.  The "OLD way" where the platform files are installed by the package is best **if** it works.
- Can run from GUI directly after install
- Icons are available even before restart
- No broken links on uninstall.

The "NEW way" where the platform files are installed on first run is still useful as it's definitely better than nothing.
In `initialize_platform()` it can exit if there is a /usr/share/applications/safeeyes.desktop.

**Comment by slgobinath** [comment] 2020-12-28 17:32
I've made the required changes in a new branch: https://github.com/slgobinath/SafeEyes/tree/fix-setup-data-files

However, several other Python projects are affected by this https://github.com/pypa/pip/issues/2874 and I am still thinking if it is okay to install platform files to `/usr/local/lib/python3.8/dist-packages` Obviously they won't be used by the system and will be removed when safeeyes is uninstalled but aren't we creating kinda redundant files?

Still I am searching for proper solution to this problem. I will update it here once I find a working solution.

**Comment by AdamPS** [comment] 2020-12-30 12:10
Great thanks.  This new approach should be a big improvement.  I don't know any way to test it before you make a release with a deb package.

I looked at the code and noticed something that didn't look quite right.
`if not os.path.exists(os.path.join(sys.prefix, "share/applications")):`
Shouldn't this test for /usr/share/applications/safeeyes.desktop rather than just /usr/share/applications/?

> but aren't we creating kinda redundant files?
Yes but who cares:-)?  Most people won't even notice.  I think there were already redundant files in 2.1.1 anyway: one copy in dist-packages and one in the .local/share.  We could raise a separate issue to try to look for a tidier solution.  However I would support releasing this fix as soon as you get a chance  - in 2.1.1 likely many users will notice that they can't start safeeyes from the GUI.

**Comment by slgobinath** [comment] 2020-12-31 00:12
> I looked at the code and noticed something that didn't look quite right.
Good catch. I am making stupid mistakes these days

I am also looking for a way to install icons as part of the Debian packaging (without relying on Python package). I will release the fix asap (hopefully by this weekend)

**Comment by slgobinath** [comment] 2020-12-31 13:35
Found a solution in Debian and merged the changes to master. I will release the fix soon
Thanks

**Comment by AdamPS** [comment] 2020-12-31 14:50
Excellent many thanks

**Comment by slgobinath** [comment] 2021-02-14 00:37
Released the fixed version 2.1.2

**Closed by slgobinath** 2021-02-14 00:37 UTC
Labels: bug, confirmed

**Comment by AdamPS** [comment] 2021-02-15 12:00
Great thanks.  I can confirm that the new version works as expected.  The file ~/.local/share/applications/safeeyes.desktop from the previous release was not deleted automatically, however I manually deleted it and it still worked.
