### ISSUE TITLE
Safe Eyes isn't visible while Showing Desktop on KDE (Meta + D)

### ISSUE THREAD

**Issue by luni3359** [slgobinath/SafeEyes#426] opened 2021-02-20 13:48 UTC
If you happen to be showing the desktop in KDE when the next break triggers, Safe Eyes won't appear even though it still goes through the break as normal. So far I've been getting around this by doing any random exercise when it happens.

**Comment by archisman-panigrahi** [comment] 2024-07-27 21:42
I am closing this since I cannot reproduce it on any of my kde 5/6 setups. If this is still relevant, please reopen and add more details about your os.

**Closed** 2024-07-27 21:42 UTC
