### ISSUE TITLE
it doesn't run

### ISSUE THREAD

**Issue by Ali-Nazarii** [slgobinath/SafeEyes#372] opened 2020-09-03 16:18 UTC
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.0.9', 'console_scripts', 'safeeyes')())
  File "/usr/bin/safeeyes", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/safeeyes/__main__.py", line 32, in <module>
    from safeeyes import Utility
  File "/usr/lib/python3.8/site-packages/safeeyes/Utility.py", line 35, in <module>
    import babel.dates
ModuleNotFoundError: No module named 'babel.dates'; 'babel' is not a package

**Comment by archisman-panigrahi** [comment] 2024-06-26 19:01
Closing since it cannot be reproduced

**Closed by archisman-panigrahi** 2024-06-26 19:01 UTC
