### ISSUE TITLE
[BUG] Frozen break screen

### ISSUE THREAD

**Issue by gorandp** [slgobinath/SafeEyes#370] opened 2020-08-06 22:41 UTC
Steps to reproduce:

1. Take a break now (or wait for programmed break)
2. Before or instantly after click Safe Eyes' tray icon
3. Wait until break screen appears
4. Select the "Quit" option from the popped options of the tray pane
5. Countdown timer is frozen and break screen is locked forever

The only way I can see my desktop is pressing Ctrl+D or the Home key to see the programs,  but if I open a window of any application the break screen appears again.
So I must restart the whole SO or close session and open it again, in order to get rid off the break screen, because I can't kill it with the console or I don't know how to.

Anyways, cool application, I've been using it for 6-7 months and it's great.

---
SO: Ubuntu 18.04.4 LTS (64bits)

**Comment by archisman-panigrahi** [comment] 2024-07-29 13:36
Is this still relevant? I cannot reproduce it in KDE Plasma 6. If not, I will close this bug report in a week.

**Comment by archisman-panigrahi** [comment] 2024-08-11 05:19
Duplicate of https://github.com/slgobinath/SafeEyes/issues/429. Fixed with https://github.com/slgobinath/SafeEyes/pull/622. Version 2.2.2 is free of this bug.

**Closed by archisman-panigrahi** 2024-08-11 05:19 UTC
