### ISSUE TITLE
Major Bug: Version 2.1.1 doesn't work on Ubunto 20.04

### ISSUE THREAD

**Issue by reni11111** [slgobinath/SafeEyes#407] opened 2020-12-30 17:21 UTC
I was using 2.0.9 which has been a great product, ubunto showed me the update and I clicked install, update was successful but on next restart it wasn't starting at all.
I tried many things and didn't work, I downloaded the source of 2.0.9 and installed again that stable version.

**Comment by slgobinath** [comment] 2020-12-31 00:10
Hi, Did you try running safeeyes from Terminal? If so, what was the output?

**Comment by lokeshpahal** [comment] 2021-01-01 10:15
@slgobinath - I am facing the same issue after the latest updates. No error in the terminal.

**Comment by slgobinath** [comment] 2021-01-01 13:36
@lokeshpahal could you pls start Safe Eyes in debug mode and share the output with me?
```
safeeyes --debug
```

There is a known issue with Safe Eyes 2.1.1 which is no desktop entries/icons created by the installer but Safe Eyes should work as usual.

**Comment by Spagol** [comment] 2021-01-05 09:01
@slgobinath - I am facing the same issue as the two guys after the latest updates on 26 Dec(from 2.0.9-1 to 2.1.1-1) No error in the terminal. I am on LMint 20.
I have found that the countdown does not work. At any time that one checks the next time of next break, it is ALWAYS 10 minutes after the current system time. I have the log, but am not sure how to attach?

**Comment by Spagol** [comment] 2021-01-05 09:02
10 minutes its only coz I have set it at 10min for latest test.

**Comment by Spagol** [comment] 2021-01-05 09:04
[safeeyes.log](https://github.com/slgobinath/SafeEyes/files/5769131/safeeyes.log)
YAY! worked out how to upload!

**Comment by krote5k** [comment] 2021-01-14 11:44
Similar problem. The program seems to restart constantly.

**Comment by mimre25** [comment] 2021-01-15 13:31
Same here on Ubuntu 20.04

```
➜  ~ safeeyes --debug
2021-01-15 14:26:07,186 [DEBUG]:[MainThread] Initialize the platform
2021-01-15 14:26:07,212 [INFO]:[MainThread] Starting Safe Eyes
2021-01-15 14:26:07,297 [INFO]:[MainThread] Initialize the break screen
2021-01-15 14:26:07,298 [INFO]:[MainThread] Load all the plugins
2021-01-15 14:26:07,298 [INFO]:[MainThread] Initialize the core
2021-01-15 14:26:07,299 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2021-01-15 14:26:07,301 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/notification/plugin.py'>
2021-01-15 14:26:07,302 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/audiblealert/plugin.py'>
2021-01-15 14:26:07,304 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py'>
2021-01-15 14:26:07,305 [INFO]:[MainThread] Successfully loaded <module 'smartpause.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/smartpause/plugin.py'>
2021-01-15 14:26:07,306 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/screensaver/plugin.py'>
2021-01-15 14:26:07,315 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/healthstats/plugin.py'>
2021-01-15 14:26:07,316 [INFO]:[MainThread] Successfully loaded <module 'mediacontrol.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/mediacontrol/plugin.py'>
2021-01-15 14:26:07,317 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2021-01-15 14:26:07,317 [DEBUG]:[MainThread] Initialize Notification plugin
2021-01-15 14:26:07,317 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2021-01-15 14:26:07,317 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2021-01-15 14:26:07,321 [DEBUG]:[MainThread] Initialize Smart Pause plugin
2021-01-15 14:26:07,321 [DEBUG]:[MainThread] Initialize Screensaver plugin
2021-01-15 14:26:07,322 [DEBUG]:[MainThread] Initialize Health Stats plugin
2021-01-15 14:26:07,322 [DEBUG]:[MainThread] Health stats will be reset at 2021-01-16 00:00:00
2021-01-15 14:26:07,324 [DEBUG]:[MainThread] Resetting the health statistics
2021-01-15 14:26:07,324 [DEBUG]:[MainThread] Health stats will be reset at 2021-01-16 00:00:00
2021-01-15 14:26:07,324 [INFO]:[MainThread] Setting up an RPC server on port 7200
2021-01-15 14:26:07,325 [INFO]:[MainThread] Start the RPC server
2021-01-15 14:26:07,325 [DEBUG]:[MainThread] Start Smart Pause plugin
2021-01-15 14:26:07,325 [INFO]:[MainThread] Start Safe Eyes core
2021-01-15 14:26:07,326 [INFO]:[WorkThread] Waiting for 30 minutes until next break
2021-01-15 14:26:07,329 [INFO]:[MainThread] Update next break information
2021-01-15 14:26:29,423 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-15 14:26:29,424 [INFO]:[MainThread] Disable Safe Eyes
2021-01-15 14:26:29,425 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-15 14:26:29,425 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-15 14:29:14,280 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-15 14:29:14,280 [INFO]:[MainThread] Start Safe Eyes core
2021-01-15 14:29:14,280 [INFO]:[WorkThread] Waiting for 30 minutes until next break
2021-01-15 14:29:14,280 [INFO]:[MainThread] Enable Safe Eyes
2021-01-15 14:29:14,281 [INFO]:[MainThread] Update next break information
2021-01-15 14:29:30,351 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-15 14:29:30,352 [INFO]:[MainThread] Disable Safe Eyes
2021-01-15 14:29:30,354 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-15 14:29:30,355 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-15 14:29:46,440 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-15 14:29:46,440 [INFO]:[MainThread] Start Safe Eyes core
2021-01-15 14:29:46,441 [INFO]:[WorkThread] Waiting for 30 minutes until next break
2021-01-15 14:29:46,441 [INFO]:[MainThread] Enable Safe Eyes
2021-01-15 14:29:46,442 [INFO]:[MainThread] Update next break information
2021-01-15 14:29:52,456 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-15 14:29:52,457 [INFO]:[MainThread] Disable Safe Eyes
2021-01-15 14:29:52,457 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-15 14:29:52,457 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-15 14:29:54,469 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-15 14:29:54,470 [INFO]:[MainThread] Start Safe Eyes core
2021-01-15 14:29:54,470 [INFO]:[WorkThread] Waiting for 30 minutes until next break
2021-01-15 14:29:54,471 [INFO]:[MainThread] Enable Safe Eyes
2021-01-15 14:29:54,472 [INFO]:[MainThread] Update next break information
^C```

**Comment by ocpodariu** [comment] 2021-01-21 17:07
Hi, I have the same issue with version 2.1.1 on Ubuntu 18.04.5.

```
$ safeeyes --debug
2021-01-21 19:01:35,645 [DEBUG]:[MainThread] Initialize the platform
2021-01-21 19:01:35,671 [INFO]:[MainThread] Starting Safe Eyes
2021-01-21 19:01:35,749 [INFO]:[MainThread] Initialize the break screen
2021-01-21 19:01:35,749 [INFO]:[MainThread] Load all the plugins
2021-01-21 19:01:35,749 [INFO]:[MainThread] Initialize the core
2021-01-21 19:01:35,751 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2021-01-21 19:01:35,753 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/notification/plugin.py'>
2021-01-21 19:01:35,754 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/audiblealert/plugin.py'>
2021-01-21 19:01:35,756 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py'>
2021-01-21 19:01:35,757 [INFO]:[MainThread] Successfully loaded <module 'smartpause.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/smartpause/plugin.py'>
2021-01-21 19:01:35,758 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/screensaver/plugin.py'>
2021-01-21 19:01:35,764 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/healthstats/plugin.py'>
2021-01-21 19:01:35,765 [INFO]:[MainThread] Successfully loaded <module 'mediacontrol.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/mediacontrol/plugin.py'>
2021-01-21 19:01:35,765 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2021-01-21 19:01:35,766 [DEBUG]:[MainThread] Initialize Notification plugin
2021-01-21 19:01:35,766 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2021-01-21 19:01:35,766 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2021-01-21 19:01:35,771 [DEBUG]:[MainThread] Initialize Smart Pause plugin
2021-01-21 19:01:35,771 [DEBUG]:[MainThread] Initialize Screensaver plugin
2021-01-21 19:01:35,771 [DEBUG]:[MainThread] Initialize Health Stats plugin
2021-01-21 19:01:35,772 [DEBUG]:[MainThread] Health stats will be reset at 2021-01-22 00:00:00
2021-01-21 19:01:35,774 [DEBUG]:[MainThread] Resetting the health statistics
2021-01-21 19:01:35,774 [DEBUG]:[MainThread] Health stats will be reset at 2021-01-22 00:00:00
2021-01-21 19:01:35,775 [INFO]:[MainThread] Setting up an RPC server on port 7200
2021-01-21 19:01:35,775 [INFO]:[MainThread] Start the RPC server
2021-01-21 19:01:35,776 [DEBUG]:[MainThread] Start Smart Pause plugin
2021-01-21 19:01:35,777 [INFO]:[MainThread] Start Safe Eyes core
2021-01-21 19:01:35,777 [INFO]:[WorkThread] Waiting for 15 minutes until next break
2021-01-21 19:01:35,779 [INFO]:[MainThread] Update next break information
2021-01-21 19:01:45,854 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-21 19:01:45,857 [INFO]:[MainThread] Disable Safe Eyes
2021-01-21 19:01:45,860 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-21 19:01:45,861 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-21 19:02:22,132 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-21 19:02:22,134 [INFO]:[MainThread] Start Safe Eyes core
2021-01-21 19:02:22,137 [INFO]:[MainThread] Enable Safe Eyes
2021-01-21 19:02:22,137 [INFO]:[WorkThread] Waiting for 15 minutes until next break
2021-01-21 19:02:22,139 [INFO]:[MainThread] Update next break information
2021-01-21 19:02:44,361 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-21 19:02:44,363 [INFO]:[MainThread] Disable Safe Eyes
2021-01-21 19:02:44,365 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-21 19:02:44,366 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-21 19:02:52,431 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-21 19:02:52,433 [INFO]:[MainThread] Start Safe Eyes core
2021-01-21 19:02:52,435 [INFO]:[MainThread] Enable Safe Eyes
2021-01-21 19:02:52,436 [INFO]:[WorkThread] Waiting for 15 minutes until next break
2021-01-21 19:02:52,438 [INFO]:[MainThread] Update next break information
```

**Comment by kulkarniniraj** [comment] 2021-01-23 16:31
Looks like some change in idle logic breaks it. Safeeyes is disableed after every few seconds of inactivity.

```
2021-01-23 21:54:33,746 [INFO]:[WorkThread] Waiting for 2 minutes until next break
2021-01-23 21:54:33,746 [INFO]:[MainThread] Update next break information
2021-01-23 21:54:44,812 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-23 21:54:44,813 [INFO]:[MainThread] Disable Safe Eyes
2021-01-23 21:54:44,813 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-23 21:54:44,813 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-23 21:56:45,397 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-23 21:56:45,399 [INFO]:[MainThread] Start Safe Eyes core
2021-01-23 21:56:45,401 [INFO]:[MainThread] Enable Safe Eyes
2021-01-23 21:56:45,401 [INFO]:[WorkThread] Waiting for 2 minutes until next break
2021-01-23 21:56:45,403 [INFO]:[MainThread] Update next break information
2021-01-23 21:57:39,717 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-23 21:57:39,717 [INFO]:[MainThread] Disable Safe Eyes
2021-01-23 21:57:39,718 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-23 21:57:39,718 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-23 21:57:41,729 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-23 21:57:41,730 [INFO]:[MainThread] Start Safe Eyes core
2021-01-23 21:57:41,732 [INFO]:[MainThread] Enable Safe Eyes
2021-01-23 21:57:41,732 [INFO]:[WorkThread] Waiting for 2 minutes until next break
2021-01-23 21:57:41,734 [INFO]:[MainThread] Update next break information
2021-01-23 21:58:21,944 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-23 21:58:21,945 [INFO]:[MainThread] Disable Safe Eyes
2021-01-23 21:58:21,945 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-23 21:58:21,945 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-23 21:58:27,972 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-23 21:58:27,973 [INFO]:[MainThread] Start Safe Eyes core
2021-01-23 21:58:27,975 [INFO]:[MainThread] Enable Safe Eyes
2021-01-23 21:58:27,975 [INFO]:[WorkThread] Waiting for 2 minutes until next break
2021-01-23 21:58:27,977 [INFO]:[MainThread] Update next break information
2021-01-23 21:58:42,052 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2021-01-23 21:58:42,052 [INFO]:[MainThread] Disable Safe Eyes
2021-01-23 21:58:42,053 [INFO]:[MainThread] Stop Safe Eyes core
2021-01-23 21:58:42,053 [INFO]:[WorkThread] Pre-break waiting is over
2021-01-23 21:58:46,077 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
2021-01-23 21:58:46,078 [INFO]:[MainThread] Start Safe Eyes core
2021-01-23 21:58:46,080 [INFO]:[MainThread] Enable Safe Eyes
2021-01-23 21:58:46,080 [INFO]:[WorkThread] Waiting for 2 minutes until next break
2021-01-23 21:58:46,082 [INFO]:[MainThread] Update next break information
```

**Comment by slgobinath** [comment] 2021-01-24 03:06
Hi,
This problem is fixed with the recent commit https://github.com/slgobinath/SafeEyes/commit/a69debf8ff0342e5235fa2a08d20e29c366c247d

You can check if it is fixed by running from the source code. Earlier I planned to release a new version with this fix but looks like there are some other issues which can be fixed in the next version. So it may take some time to release the next version with the fix.

**Comment by slgobinath** [comment] 2021-01-24 03:08
Duplicate of https://github.com/slgobinath/SafeEyes/issues/407

**Closed by slgobinath** 2021-01-24 03:08 UTC
Labels: bug, confirmed, duplicate

**Comment by reni11111** [comment] 2021-01-25 12:29
LOLL how is it duplicated,  this is posted first

**Comment by slgobinath** [comment] 2021-01-27 03:54
@reni11111 sorry my bad :laughing: 
I didn't notice the order but the other issue had some comments mentioning temporary solution so I just marked this duplicate. Hope no offence is taken :smile:
