### ISSUE TITLE
Pomodore mode?

### ISSUE THREAD

**Issue by dkobashi** [slgobinath/SafeEyes#212] opened 2017-11-09 14:20 UTC
I am trying to use this program on Linux. I want to use this program for pomodore though this program may not be designed for the purpose originally, but when I tried to set up the program, I found out that I could not increase the break duration longer than 60 seconds for short break. I would like it to be 5 min for 25 min interval (1 pomodore) and multiple pomodores for long break.  Would it be possible to change it?

Also, it would be great if this program shows how many short intervals (i.e. pomodore) we have today on screen or setting e.g. 1/8 where 8 is the number of short interval selected on the setting etc.

I found the above functions useful when I used some program on Mac designed for pomodore; however, there is none for linux. This is one of the few close to what I need. 

Thanks in advance,

**Comment by slgobinath** [comment] 2018-01-05 12:23
Hi,
I agree that it will reduce the number of applications you need. I am against to adding this as a core feature since it will deviate the purpose of Safe Eyes. However, I will consider it as a low priority [third-party plugin](https://github.com/slgobinath/safeeyes-plugins).

**Comment by slgobinath** [comment] 2019-01-12 01:41
Closing as duplicate of #292 though it was the first request

**Closed by slgobinath** 2019-01-12 01:41 UTC
Labels: enhancement
