### ISSUE TITLE
Crashes for Ubuntu 24.04

### ISSUE THREAD

**Issue by Nefcanto** [slgobinath/SafeEyes#575] opened 2024-05-07 04:59 UTC
**Describe the bug**
I search the app, then find it, then click on it to open it. I get the crash screen.
Then I run it from the command line using `safeeyes` command:

And this is what I get:

```
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.5', 'console_scripts', 'safeeyes')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/safeeyes", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/safeeyes/__main__.py", line 32, in <module>
    from safeeyes import utility
  File "/usr/lib/python3/dist-packages/safeeyes/utility.py", line 24, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**To Reproduce**
1. Install Ubuntu 24.04
2. Install Safe Eyes
3. Run it

**Expected behavior**
Safe Eyes should work on Ubuntu 24.04

**Desktop (please complete the following information):**
 - OS: 24.04 LTS (Noble Numbat)
 - Desktop Env: ubuntu:GNOME
 - Version I can't get the version. It crashes. But I have installed it using `sudo apt install safeeyes -y` which means it must be the latest now (2.1.6 at this time)

**Debug Log**
Can not be run. Prints the same error.

**Comment by deltragon** [comment] 2024-05-17 14:47
This is already fixed in master: #544
However, it needs a new release to fix it, see https://github.com/slgobinath/SafeEyes/issues/552.
This can be closed as a duplicate of that bug.

**Comment by Nefcanto** [comment] 2024-06-08 09:56
@deltragon do you have access to publish a new release? If it's solved then it's so sad that the entire community is waiting for a simple publish.

**Comment by archisman-panigrahi** [comment] 2024-06-09 01:58
The new PPA is ready.
```
sudo add-apt-repository ppa:safeeyes-team/safeeyes
sudo apt update
sudo apt install safeeyes
```

**Comment by Nefcanto** [comment] 2024-06-09 04:50
@archisman-panigrahi, thank you so much. I worked.

**Closed** 2024-06-09 05:22 UTC
Labels: bug
