### ISSUE TITLE
Translated version crashes

### ISSUE THREAD

**Issue by nam1962** [slgobinath/SafeEyes#91] opened 2017-03-09 11:36 UTC
I installed SafeEyes on my manjaro unstable.
Fine job, works well, but only in english.
In french for instance, I see the warning popup and... nothing, the program stops and disappears from the panel.

**Comment by slgobinath** [comment] 2017-03-09 15:47
Hi,
I have tested it in Manjaro 16.10.3 Fringilla with KDE and couldn't reproduce this issue. Could you please run Safe Eyes from the terminal using the following command and let me know the error message in terminal.
```
/usr/lib/safeeyes/safeeyes
```

Also please share the log file contents once Safe Eyes stops. Command to read the log file is given below.
```
cat ~/.config/safeeyes/safeeyes.log
```

**Comment by nam1962** [comment] 2017-03-09 16:17
you know what ?
It didn't rehappen ! I'm ashamed there ;)
(Its not iso as some Mnajaro updates came this morning.
Just in case : 
`~]$ /usr/lib/safeeyes/safeeyes

(safeeyes:30310): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`
`~]$ cat ~/.config/safeeyes/safeeyes.log
2017-03-09 17:16:42,589 [INFO] Starting Safe Eyes
2017-03-09 17:16:42,589 [INFO] Initialize the tray icon
2017-03-09 17:16:42,598 [INFO] Initialize the break screen
2017-03-09 17:16:42,598 [INFO] Initialize the core
2017-03-09 17:16:42,598 [INFO] Scheduling next break
2017-03-09 17:16:42,599 [INFO] Update next break information
2017-03-09 17:16:42,599 [INFO] Initialize the notification
2017-03-09 17:16:42,659 [INFO] Pre-break waiting for 15 minutes
`

**Comment by slgobinath** [comment] 2017-03-09 16:31
Thanks for letting me know. Then I close this issue for the moment. If it happens again, feel free to reopen it.

**Closed by slgobinath** 2017-03-09 16:31 UTC
