### ISSUE TITLE
SafeEyes won't launch, throwing  `AttributeError: module 'gi' has no attribute 'require_version'`

### ISSUE THREAD

**Issue by poperigby** [slgobinath/SafeEyes#493] opened 2022-11-29 01:35 UTC
**Describe the bug**
I've installed the SafeEyes from the AUR with `paru -S safeeyes`. When I try to launch it, it crashes with this error:
```python
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.3', 'console_scripts', 'safeeyes')())
  File "/usr/bin/safeeyes", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/safeeyes/__main__.py", line 32, in <module>
    from safeeyes import utility
  File "/usr/lib/python3.10/site-packages/safeeyes/utility.py", line 43, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
``` 

**To Reproduce**
1. Install SafeEyes
2. Launch SafeEyes from the terminal

**Expected behavior**
SafeEyes launches

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Desktop Env: KDE Plasma
 - Version: 2.1.3

**Comment by nifadyev** [comment] 2024-01-16 12:26
Hey @poperigby , is the issue still relevant? Have you tried to update the latest version?

**Comment by poperigby** [comment] 2024-01-16 19:38
I no longer use this AUR version, so you can probably just close this.

**Comment by nifadyev** [comment] 2024-01-17 06:16
Thanks @poperigby 
@AdamPS , I suppose this issue should be examined on actual version before closing it

**Comment by archisman-panigrahi** [comment] 2024-06-26 19:11
Closing since it cannot anymore be reproduced in Arch.

**Closed by archisman-panigrahi** 2024-06-26 19:11 UTC
Labels: bug
