### ISSUE TITLE
arch-linux black-notification window is not showing up

### ISSUE THREAD

**Issue by OromeNahar** [slgobinath/SafeEyes#72] opened 2017-02-14 18:55 UTC
I think notification-thing-git is a missing dependency for Arch-Linux. 

This is the message before I installed notification-thing-git

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/safeeyes/SafeEyesCore.py", line 204, in __notify_and_start_break
    self.show_notification()
  File "/usr/bin/safeeyes", line 68, in show_notification
    notification.show(config['pre_break_warning_time'])
  File "/usr/lib/safeeyes/Notification.py", line 51, in show
    self.notification.show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)

After installing notification-thing-git I get this message sometimes, I am not sure when safeeyes crashes:

[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
python2: xcb_io.c:732: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
[1]    23791 abort (core dumped)  safeeyes

**Comment by slgobinath** [comment] 2017-02-15 01:20
I will test it in my Arch testing vm. The second issue seems like something similar to graphics (Based on Google search). Are you using any specific graphics?

**Comment by OromeNahar** [comment] 2017-02-15 08:54
I am using a IBM T60, 2007, 32 Bit Machine.
I am not sure which graphics is installed. I will check it later.
I think I have a problem with my x-server. I got some more messeges:

(safeeyes:1117): Gdk-ERROR **: The program 'safeeyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadImplementation (server does not implement operation)'.
  (Details: serial 12297 error_code 17 request_code 20 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[1]    1117 trace trap (core dumped)  safeeyes


I will check later what is the problem and I will post it here.
Maybe u have an idea what the problem is

**Comment by OromeNahar** [comment] 2017-02-15 13:53
My graphics is a Mobility Radeon X1400
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV515/M54 [Mobility Radeon X1400]

**Comment by slgobinath** [comment] 2017-02-15 21:00
The bug is identified and the fix will be released soon.

Thanks for reporting it.

**Comment by OromeNahar** [comment] 2017-02-15 21:11
Okay, no Problem.
On my big tower is safeeyes running perfectly. Arch Linux as well. I guess it is a problem based on the communication with the Notification-Server?! Is it correct?

**Comment by slgobinath** [comment] 2017-02-15 21:15
The problem is calling [is_active_window_skipped](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/safeeyes/Utility.py#L69) method from a separate thread at [SafeEyesCore.py#L215](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/safeeyes/SafeEyesCore.py#L215). Earlier I commented well about this issue in the SafeEyesCore.py. When I moved this method into the Utility.py, I forgot this issue :-) I will release the new version within few hours.

**Comment by slgobinath** [comment] 2017-02-15 23:32
The issue is fixed with https://github.com/slgobinath/SafeEyes/commit/f20b9602fce546735b0275d4ddebd59c15a3b554. But I want to test it further before releasing the new version. If you like, you can apply the patch by manually replacing the modified files. I will release the new version within 48 hours.

**Comment by slgobinath** [comment] 2017-02-18 15:53
I have released the fix in [v1.1.8](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.8) (Still the AUR is not updated. Need to install manually). Could you please test the behavior and let me know the status?

Thanks

**Closed** 2017-03-05 17:15 UTC
Labels: bug, confirmed
