### ISSUE TITLE
GTK error "Argument 0 does not allow None as a value" in Linux

### ISSUE THREAD

**Issue by h5rdly** [slgobinath/SafeEyes#467] opened 2021-10-16 09:19 UTC
Safeeyes 2.1.3
OpenSUSE Tumbleweed

Running safeeyes from the command line, I get:
```
user@localhost:~> safeeyes
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.3', 'console_scripts', 'safeeyes')())
  File "/usr/lib/python3.8/site-packages/safeeyes/__main__.py", line 147, in main
    safe_eyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3.8/site-packages/safeeyes/safeeyes.py", line 84, in __init__
    self.break_screen = BreakScreen(
  File "/usr/lib/python3.8/site-packages/safeeyes/ui/break_screen.py", line 62, in __init__
    Gtk.StyleContext.add_provider_for_screen(Gdk.Screen.get_default(), css_provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
TypeError: Argument 0 does not allow None as a value
```

I'm trying to set up a Linux environment on a new computer, not having safeeyes gives me all the bad side effects of staring at the screen..

**Comment by archisman-panigrahi** [comment] 2024-07-15 15:48
Is this still valid with latest version (2.2.1)? If not, I will close the issue in one week.

**Comment by h5rdly** [comment] 2024-07-17 07:41
I installed it on my current Opensuse Tumbleweed today using `sudo zypper install safeeyes`. 

It shows in the KDE app menu, but nothing happens when you select it.

**Comment by deltragon** [comment] 2024-07-17 09:13
Hmm, I assume you are on KDE Wayland? Are you using the "Plasma (Wayland)" or "Plasma (Wayland Full)" session? (Assuming that split still exists for Plasma 6).

**Comment by archisman-panigrahi** [comment] 2024-07-17 13:38
Ensure that you have installed the latest version of safeeyes 2.2.1. Then run `safeeyes` on terminal and post the full error message.

**Comment by archisman-panigrahi** [comment] 2024-07-17 14:40
> I can pull that fix out into a separate PR, and submit it so it can be tested.

Unless it involves too much work, and unless it breaks anything without the rest of the PR, please send a different PR for fix so that it can be tested. I have KDE 6.1 in Arch (I was using X.Org so far), and I can test it too.

**Comment by deltragon** [comment] 2024-07-17 15:52
So, it turns out that was a different error - when running in a pure Wayland session (no XWayland) it throws an error here:
![image](https://github.com/user-attachments/assets/01bc102d-a169-4ad2-9a21-7825efc8d218)
Which is a few lines above - so I would have kept that in the gtk4 PR.

However, it could have to do with this: https://stackoverflow.com/a/43650391/3067153 - according to that, `gtk_init()` must be called before any other call to Gtk.
Quoting the [docs](https://docs.gtk.org/gtk3/func.init.html),
> And if you are using GtkApplication, you don’t have to call any of the initialization functions either; the GtkApplication::startup handler does it for you.

However, we call `BreakScreen.__init__` inside of `SafeEyes.__init__`, which happens before the `do_startup` handler. 
(The switch to Gtk.Application in https://github.com/slgobinath/SafeEyes/pull/560 didn't change anything there - there, `BreakScreen.__init__` was called before `Gtk.main()`.)

I've submitted https://github.com/slgobinath/SafeEyes/pull/610 that changes the order we handle things.

**Comment by deltragon** [comment] 2024-07-17 16:40
Actually, it turns out, if I do `zypper install safeeyes` in OpenSuse Tumbleweed, i get this error:
![image](https://github.com/user-attachments/assets/e834da8e-5fb7-4a64-8150-6a3d2ac169f0)
With `zypper install python3-packaging`, it works.
So this might just be a simple packaging issue.
I don't have the time to go and report it now, but I will in the next few days (unless someone beats me to it).

**Comment by archisman-panigrahi** [comment] 2024-07-17 16:51
@deltragon I added a comment to my existing bug report https://bugzilla.opensuse.org/show_bug.cgi?id=1227743 I don't know if I should have created a new bug report.

**Comment by h5rdly** [comment] 2024-07-18 14:37
> Actually, it turns out, if I do `zypper install safeeyes` in OpenSuse Tumbleweed, i get this error: ![image](https://private-user-images.githubusercontent.com/11904241/349583844-e834da8e-5fb7-4a64-8150-6a3d2ac169f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTM3MzAsIm5iZiI6MTcyMTMxMzQzMCwicGF0aCI6Ii8xMTkwNDI0MS8zNDk1ODM4NDQtZTgzNGRhOGUtNWZiNy00YTY0LTgxNTAtNmEzZDJhYzE2OWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE0MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTllMmQwMjRjYWQ5MDE0OTJhYjNiNzcwY2UwYzk4NThiZDU3MDk4NmQ1ODE5MGRjMjU0M2JjODQ4ZThiODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GD6-cW6fLKygv4-gY0kk9m5cefzTx-PMWxt-OLtakS0) With `zypper install python3-packaging`, it works. So this might just be a simple packaging issue. I don't have the time to go and report it now, but I will in the next few days (unless someone beats me to it).

I ran `pip3 install --break-system-packages packaging` and it starts for me as well, thanks!

**Comment by archisman-panigrahi** [comment] 2024-07-18 14:55
So, I guess the problem is fixed, and only `python3-packaging` needs to be added as a dependency.

In that case, is https://github.com/slgobinath/SafeEyes/pull/610 necessary?

> So, it turns out that was a different error - when running in a pure Wayland session (no XWayland) it throws an error here:

I think this is a different issue. @deltragon Can you create a new issue?

**Comment by deltragon** [comment] 2024-07-25 18:57
@archisman-panigrahi The issue in the pure Wayland session already is tracked here: https://github.com/slgobinath/SafeEyes/issues/367
I think #610 still makes sense to do, because the current situation does violate what the Gtk docs say you should do.

**Closed** 2024-08-04 22:28 UTC
Labels: bug
