### ISSUE TITLE
Ubuntu 17.10 - I cannot start safeeyes

### ISSUE THREAD

**Issue by eruizg** [slgobinath/SafeEyes#233] opened 2018-01-23 22:13 UTC
After try all available methods I cannot start safeeyes, after an apparently right installation the message I get after run safeeyes --debug is:

Traceback (most recent call last):
  File "/usr/local/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.2', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/safeeyes-2.0.2-py2.7.egg/safeeyes/__main__.py", line 34, in <module>
    from safeeyes.SafeEyes import SafeEyes
  File "/usr/local/lib/python2.7/dist-packages/safeeyes-2.0.2-py2.7.egg/safeeyes/SafeEyes.py", line 34, in <module>
    from safeeyes.rpc import RPCServer
  File "/usr/local/lib/python2.7/dist-packages/safeeyes-2.0.2-py2.7.egg/safeeyes/rpc.py", line 25, in <module>
    from xmlrpc.server import SimpleXMLRPCServer
ImportError: No module named xmlrpc.server

**Comment by slgobinath** [comment] 2018-01-23 23:32
`python2.7`!!!
Safe Eyes requires Python 3. How did you install Safe Eyes?

**Comment by slgobinath** [comment] 2018-02-09 15:45
Closing this issue because the problem is with Python version

**Closed** 2018-02-09 15:44 UTC
