### ISSUE TITLE
Don't run fullscreen in DWM

### ISSUE THREAD

**Issue by mrbooshehri** [slgobinath/SafeEyes#414] opened 2021-01-17 14:07 UTC
more information:
OS: Ubuntu 20.04
WM: DWM 6.1

and window rule is "isfloating" in dwm config.

screenshot:
https://imgbox.com/blzbUrpg

**Comment by kdkasad** [comment] 2021-03-21 00:59
I'm getting the same problem. The SafeEyes windows just show up as normal windows, although they do take the keyboard focus. I can still interact with other windows using the mouse, which is only a problem caused by SafeEyes not being fullscreen.

**Comment by archisman-panigrahi** [comment] 2024-06-26 18:56
This seems to be more of a DWM specific customization issue rather than a safeeyes issue. Can you create another window rule to make safe eyes fullscreen?

**Comment by archisman-panigrahi** [comment] 2024-07-27 21:47
Is this bug still relevant? I will close it otherwise.

**Comment by archisman-panigrahi** [comment] 2024-08-04 22:08
Closing due to inactivity

**Closed** 2024-08-04 22:07 UTC
