### ISSUE TITLE
Stops working when the night light is on

### ISSUE THREAD

**Issue by AminDar** [slgobinath/SafeEyes#508] opened 2023-02-10 09:00 UTC
**Describe the bug**
It work perfectly fine as long as the night light is off. Otherwise it doesn't show the break window

**To Reproduce**
1. Go to settings
2. Go to Displays
3. Click in Night Light
4. Turn the night light on

**Desktop (please complete the following information):**
 - OS:  22.04.1 LTS
 - Desktop  Gnome,
 - safeeyes 2.1.4

**Debug Log**
Run the Safe Eyes using `safeeyes --debug` command attach the ~/safeeyes.log` file.

[safeeyes.log](https://github.com/slgobinath/SafeEyes/files/10705546/safeeyes.log)

**Comment by rayniel95** [comment] 2023-03-08 19:44
I have the same problem. It was working the past week, this week I started using light night and safe eyes icon seem like deactivate sometimes.

**Comment by rayniel95** [comment] 2024-01-17 12:56
Mmmmmmmm.......... I dont know. After the issue I started using gnome-pomodoro and right now I am using linux mint with the last version of safe eyes, but linux mint use redshift for the night light, so, my problem is solved. Maybe you can close this issues until have more info.

**Comment by nifadyev** [comment] 2024-01-17 13:38
Thank you @rayniel95 , anyway it would be better to check described behavior before closing the issue

**Comment by AminDar** [comment] 2024-01-30 14:13
I switched to another app also.But I'll try to use in the next couple of days to see if anything changed

**Comment by archisman-panigrahi** [comment] 2024-09-22 03:49
I cannot reproduce this with the latest version of safeeyes on Ubuntu 24.04 night light, and also on Arch Linux with KDE night light.

If someone can reproduce, then please reopen.

**Closed by archisman-panigrahi** 2024-09-22 03:49 UTC
Labels: bug
