### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by mrhieu059** [slgobinath/SafeEyes#155] opened 2017-06-12 16:34 UTC
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==1.2.1', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/safeeyes-1.2.1-py3.6.egg/safeeyes/__main__.py", line 21, in <module>
    import os, gi, json, dbus, logging, operator, psutil, sys
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

How to fix it?
I have reinstall it few times, but it made a mistake.
Method 1: i use yaourt and install full package dependencies
Method 2: i install individual dependencies separately
I use antergos with kernel 4.11.3-1
Please help me

**Comment by mrhieu059** [comment] 2017-06-12 16:35
![screenshot_2017-06-12_23-34-43](https://user-images.githubusercontent.com/29304809/27044439-c7d33368-4fc7-11e7-80b8-d765da707638.png)

**Comment by slgobinath** [comment] 2017-06-12 18:01
This is not a bug in Safe Eyes but a problem with `gi` module. I think the current `gi` installed in your system is for Python 2. Could you please remove the existing gi and install `python3-gi` again (I am not sure whether it fixes the problem but I think it should work).

**Comment by mrhieu059** [comment] 2017-06-13 01:44
Wow...It's working 
Thank you a lot :D

**Comment by slgobinath** [comment] 2017-06-13 10:59
It's my pleasure :-)
Thanks for confirming. I am closing this issue.

**Closed by slgobinath** 2017-06-13 10:59 UTC

**Comment by ToJen** [comment] 2017-12-23 00:07
@mrhieu059 when you removed `gi` with `pip uninstall gi`, did you change anything else in the code?
