### ISSUE TITLE
less blue

### ISSUE THREAD

**Issue by boxesofdead** [slgobinath/SafeEyes#172] opened 2017-07-12 14:05 UTC
Please consider a feature to filter out more blue light as time unfolds to midnight.

Perhaps as an overlay of the color opposite of blue -- my XPosed plugin uses orange

**Comment by radek-sprta** [comment] 2017-07-13 13:08
Wouldn't that cause trouble when already using something like Redshift?

**Comment by slgobinath** [comment] 2017-07-13 15:17
I am currently using Redshift and I didn't think about having that feature in Safe Eyes until this feature request. I am quite satisfied with Redshift and adding a new feature is just a duplicate of work and increase the chance of bugs and more issues.
On the other hand adding this feature as an optional feature will reduce the number of apps required.

Whether to add this feature or not is open for debate :-)

**Comment by radek-sprta** [comment] 2017-07-14 17:24
I think having this is redundant. Especially since with the move to Wayland, desktop environment are starting to implement this feature themselves.

**Comment by slgobinath** [comment] 2017-07-14 20:13
I agree with @radek-sprta. Already Gnome has added this feature and KDE is implementing it (or already available) so it is better to let them handle it.
WDYT @boxesofdead?

**Comment by slgobinath** [comment] 2017-07-30 15:54
Since this feature is being added to most of the desktop environments and there are enough tools handling this, I close it as a redundant work load.

**Closed by slgobinath** 2017-07-30 15:54 UTC
Labels: enhancement, wontfix
